name: Snake Game 🐍

on:
  schedule:
    - cron: "0 */5 * * *" # Executa a cada 5 horas
  workflow_dispatch: # Permite executar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Gerar Snake
        uses: Platane/snk@master
        with:
          github_user_name: JhoelDiego2
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Verificar status dos arquivos
        run: git status

      - name: Commit e Push do Snake para branch master
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # ⚠️ CORRETO: "github_token", NÃO "token"
          branch: master
          force: true
